services:
  - type: web
    name: pdl-rcf
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: REPLIT_MODE
        value: false
      - key: DEBUG_MODE
        value: false
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    region: oregon
    # Especificar que não é Docker
    dockerfilePath: null 